package io.github.maskmasteruk.supabase.auth.Enums;

/**
 * Defines the supported Multi-Factor Authentication (MFA) factor types.
 * <p>
 * This enum is used to specify the type of MFA factor used for authentication,
 * such as a Time-based One-Time Password (TOTP) authenticator app or
 * SMS-based phone verification.
 */
public enum FactorType {

    /**
     * A Time-based One-Time Password (TOTP) factor generated by an
     * authenticator application.
     */
    TOTP("totp"),

    /**
     * A Web Authentication (WebAuthn) factor that uses a hardware security key
     * or platform authenticator, such as a passkey, for multi-factor authentication.
     */
    WEBAUTHN("webauthn"),

    /**
     * A phone-based factor that uses SMS for verification.
     */
    PHONE("phone");

    private final String value;

    /**
     * Creates a new factor type.
     *
     * @param value The string value used by the Supabase Auth API.
     */
    FactorType(String value) {
        this.value = value;
    }

    /**
     * Gets the string representation of this factor type.
     *
     * @return The API value of the factor type.
     */
    public String getValue() {
        return value;
    }

    /**
     * Returns the {@link FactorType} corresponding to the specified API value.
     *
     * @param value The factor type value returned by the Supabase Auth API.
     * @return The matching {@link FactorType}, or {@code null} if no matching type exists.
     */
    public static FactorType fromValue(String value) {
        if (value == null) {
            return null;
        }

        for (FactorType type : values()) {
            if (type.value.equalsIgnoreCase(value)) {
                return type;
            }
        }

        return null;
    }
}